name: build-docker-ghcr
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g. v0.1.1)'
        required: true
        type: string
      release_tag_latest:
        description: 'Alias tag as latest'
        required: false
        type: boolean
        default: true
      push_image:
        description: 'Push image to GHCR'
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Docker tags
        id: docker_tags
        run: |
          RELEASE_TAG="ghcr.io/${{ github.repository_owner }}/zerowork-kasmvnc:${{ inputs.release_tag }}"
          if [ "${{ inputs.release_tag_latest }}" = "true" ]; then
            LATEST_TAG="ghcr.io/${{ github.repository_owner }}/zerowork-kasmvnc:latest"
            ALL_TAGS="$RELEASE_TAG,$LATEST_TAG"
          else
            ALL_TAGS="$RELEASE_TAG"
          fi
          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "latest_tag=${LATEST_TAG:-}" >> $GITHUB_OUTPUT
          echo "all_tags=$ALL_TAGS" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          context: .
          push: ${{ inputs.push_image }}
          tags: ${{ steps.docker_tags.outputs.all_tags }}
          build-args: |
            APP_VERSION=${{ inputs.release_tag }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/zerowork-kasmvnc:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/zerowork-kasmvnc:buildcache,mode=max

      - name: Image built
        run: echo "Docker image build completed for"
